### ISSUE TITLE
Summary of deprecated Rockons from open issues list

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockon-registry#281]
Keeping a recent list of Rockons that should probably be cleaned up (and replaced where still applicable) based on current open issues:

- [x] NZBHydra - rockstor#273 - replaced with NZBHydra2
- [x] ZoneMinder - rockstor#260 - 1.29 image unmaintained - replaced with ZoneMinder - latest
- [x] ZoneMinder-1.30 - rockstor#260 - replaced with ZoneMinder - latest
- [x] TFTP Server - rockstor#257 - image not maintained for 4 yrs
- [x] Plexpy - rockstor#255 - replaced with Tautulli
- [x] Koel - rockstor#254 not on repo anymore
- [x] Cardigann - rockstor#253 replaced by Jackett
- [x] ~~Discourse - rockstor#185 base image not available, replaced by Discourse, new design~~
- [x] Logitech Media Server ver. 7.9.4 - rockstor#282 move from pinned stable version to latest tag for less Rockon maintenance

@FroggyFlox, @phillxnet if you agree, I can submit a pull request for all of these together (or some of them), or individually. Some of the old ones, we should probably remove out of principle, as unmaintained docker images can be a security issue if they rely on old build components that might have been patched in the meantime ...

**Comment by phillxnet** [comment]
@Hooverdan96 This is some valuable work here. I'm super keen to clear out as many non functional or deprecated / abandoned Rock-ons as possible. Especially as we move towards the new 4 release. @FroggyFlox is master of Rock-ons so I'll defer to his say on this one. But I'm certainly game for a block removal of Rock-ons to get things in a better shape. We have had a number of reports of broken / old rockons and it's a bad user experience as one doesn't know, initially, if it's a Rockstor 'thing' or the collection of old rockons you may have tried 'thing'.

As for #185 it's not likely to get any attention soon and the nature of the 'new design' docker image and the very special treatment it requires means it's likely now beyond trivial to re-incorporate it so I'd definitely just delete the Discourse rockon given the special treatment it needs in it's current docker form, i.e. wrapper commands etc.

I did add to the docs a request to remove, as well as add, rock-ons so this issue is in alignment to that request as I see it.
https://github.com/rockstor/rockstor-doc/pull/239

Cheers.

**Comment by FroggyFlox** [comment]
Hi @Hooverdan96,

I just now realized I never followed-up on your work here; please accept my sincere apologies as that was probably a lot of time needed to summarize all this information. I really dropped the ball here and should have let that one slip out of my mind.

I completely agree with you and @phillxnet and believe we should simply deprecate all these in a single PR as that would be a lot simpler and clearer as well. Let us know if you are still onboard and willing to take care of it; no worry of course if you can't and I'll take care of it. 

Thanks, and sorry again for not getting to this earlier.

**Comment by phillxnet** [comment]
@FroggyFlox @Hooverdan96 I've now removed the discourse rock-on and have edited this issues original text accordingly.
Although the changes to the repo have not yet been pushed to procution. @FroggyFlox I thought it best to await a few more changes before doing this. Maybe some more rock-on removals as per this issue?

**Comment by FroggyFlox** [comment]
Thanks a lot, @phillxnet !

> @FroggyFlox I thought it best to await a few more changes before doing this. Maybe some more rock-on removals as per this issue?

Yeah, I tend to prefer to combine a few merges together so that users don't have to always click on the "Update" button in their web-UI repeatedly.

**Comment by phillxnet** [comment]
@FroggyFlox So am I correct in thinking that we can simply remove all the remaining Rock-ons specified here by @Hooverdan96 ?
In which case I can jump on that one and we can get this issue sorted.

**Comment by FroggyFlox** [comment]
> @FroggyFlox So am I correct in thinking that we can simply remove all the remaining Rock-ons specified here by @Hooverdan96 ? In which case I can jump on that one and we can get this issue sorted.

Yes, that was my latest thought on it, indeed. @Hooverdan96 was careful in picking these and I agree with all the points/justifications they made in selecting those.

**Comment by phillxnet** [comment]
@FroggyFlox @Hooverdan96 Thanks.
OK, I'll assign myself and see to this later today before jumping back on my current docs mission.

**Comment by phillxnet** [comment]
I am currently working on this issue.
